server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geraldoms/config-repository.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
